version: '3'
services:

  redis:
    image: redis
    ports:
      - '6380:6379'

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5436:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: sh -c "sleep 3 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    ports:
      - '8001:8000'
    depends_on:
      - db

  celery:
    build: .
    tty: true
    command: sh -c "sleep 10 && celery -A config worker -l INFO"
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: sh -c "sleep 11 && celery -A config beat -l info -S django"
    depends_on:
      - redis
      - app

volumes:
  pg_data: