# Generated by Django 4.2.5 on 2023-10-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paystripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_name_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id цены'),
        ),
    ]
