# Generated by Django 4.2.5 on 2023-10-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_product_stripe_name_id_product_stripe_price_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
