# Generated by Django 4.2.5 on 2023-10-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paystripe',
            options={'ordering': ('id',), 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.RemoveField(
            model_name='paystripe',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='paystripe',
            name='stripe_payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на платеж'),
        ),
        migrations.AddField(
            model_name='paystripe',
            name='stripe_payment_link_id',
            field=models.CharField(default=0, editable=False, max_length=255, unique=True, verbose_name='id ссылки на платеж'),
            preserve_default=False,
        ),
    ]
