# Generated by Django 4.2.5 on 2023-10-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paystripe_options_remove_paystripe_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystripe',
            name='stripe_payment_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='id платежа'),
        ),
        migrations.AlterField(
            model_name='paystripe',
            name='stripe_payment_link_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='id ссылки на платеж'),
        ),
    ]
