# Generated by Django 4.2.5 on 2023-10-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paystripe_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paystripe',
            options={'ordering': ('id',), 'verbose_name': 'платеж stripe', 'verbose_name_plural': 'платежи stripe'},
        ),
    ]
