# Generated by Django 4.2.5 on 2023-10-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_paystripe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystripe',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.product', verbose_name='продукт'),
        ),
    ]
