# Generated by Django 4.2.5 on 2023-10-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=150, verbose_name='название')),
                ('course_description', models.TextField(verbose_name='описание')),
                ('course_avatar', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='аватар')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('course_title',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=150, verbose_name='название')),
                ('lesson_description', models.TextField(verbose_name='описание')),
                ('lesson_avatar', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='аватар')),
                ('lesson_video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='courses.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('lesson_title',),
            },
        ),
    ]
