# Generated by Django 4.2.5 on 2023-10-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_lesson_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_owner',
            new_name='course',
        ),
    ]
