# Generated by Django 4.2.5 on 2023-10-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_owner',
            new_name='owner',
        ),
    ]
