# Generated by Django 4.2.5 on 2023-10-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_datetime_changing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего изменения'),
        ),
    ]
